export enum Role {
	GUEST = 'GUEST',
	BUYER = 'BUYER',
	SELLER = 'SELLER',
	MODERATOR = 'MODERATOR',
	ADMIN = 'ADMIN',
}

export enum SellerVerificationStatus {
	DRAFT = 'DRAFT',
	PENDING = 'PENDING',
	UNDER_REVIEW = 'UNDER_REVIEW',
	APPROVED = 'APPROVED',
	REJECTED = 'REJECTED',
	BLOCKED = 'BLOCKED',
}

export enum ProductStatus {
	DRAFT = 'DRAFT',
	PENDING_MODERATION = 'PENDING_MODERATION',
	APPROVED = 'APPROVED',
	REJECTED = 'REJECTED',
	ARCHIVED = 'ARCHIVED',
	BLOCKED = 'BLOCKED',
	DISABLED = 'DISABLED',
	ENABLED = 'ENABLED',
}

export enum OrderStatus {
	PENDING = 'PENDING',
	CONFIRMED = 'CONFIRMED',
	SHIPPED = 'SHIPPED',
	DELIVERED = 'DELIVERED',
	CANCELLED = 'CANCELLED',
	REFUNDED = 'REFUNDED',
}

export enum PaymentStatus {
	PENDING = 'PENDING',
	AUTHORIZED = 'AUTHORIZED',
	PAID = 'PAID',
	IN_ESCROW = 'IN_ESCROW',
	FAILED = 'FAILED',
	REFUNDED = 'REFUNDED',
	CHARGEBACK = 'CHARGEBACK',
	CANCELED = 'CANCELED',
}

export enum PayoutStatus {
	ON_HOLD = 'ON_HOLD',
	ELIGIBLE_FOR_RELEASE = 'ELIGIBLE_FOR_RELEASE',
	RELEASED = 'RELEASED',
	WITHDRAWN = 'WITHDRAWN',
	BLOCKED = 'BLOCKED',
	REFUNDED = 'REFUNDED',
}

export enum DeliveryStatus {
	PENDING = 'PENDING',
	PACKED = 'PACKED',
	SENT = 'SENT',
	IN_TRANSIT = 'IN_TRANSIT',
	DELIVERED = 'DELIVERED',
	NOT_RECEIVED = 'NOT_RECEIVED',
	RETURNED = 'RETURNED',
}

export enum DeliveryMethod {
	COURIER = 'COURIER',
	BRANCH_PICKUP = 'BRANCH_PICKUP',
	SELF_PICKUP = 'SELF_PICKUP',
}

export enum PaymentMethod {
	CARD = 'CARD',
	CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
	BANK_TRANSFER = 'BANK_TRANSFER',
}

export enum ComplaintStatus {
	NEW = 'NEW',
	IN_REVIEW = 'IN_REVIEW',
	RESOLVED = 'RESOLVED',
	REJECTED = 'REJECTED',
}

export enum ComplaintTarget {
	PRODUCT = 'PRODUCT',
	SELLER = 'SELLER',
	BUYER = 'BUYER',
	REVIEW = 'REVIEW',
}

export enum FeedbackCategory {
	BUG = 'BUG',
	FEATURE = 'FEATURE',
	UX = 'UX',
	OTHER = 'OTHER',
}

export enum FeedbackStatus {
	NEW = 'NEW',
	UNDER_REVIEW = 'UNDER_REVIEW',
	ACKNOWLEDGED = 'ACKNOWLEDGED',
	PLANNED = 'PLANNED',
	RESOLVED = 'RESOLVED',
	DISMISSED = 'DISMISSED',
}

export enum ReleaseNoteStatus {
	DRAFT = 'DRAFT',
	PUBLISHED = 'PUBLISHED',
}

export enum ChatType {
	MARKETPLACE = 'MARKETPLACE',
	SUPPORT = 'SUPPORT',
}

export enum SupportChatStatus {
	OPEN = 'OPEN',
	IN_PROGRESS = 'IN_PROGRESS',
	RESOLVED = 'RESOLVED',
	CLOSED = 'CLOSED',
}

export enum Language {
	EN = 'en',
	UK = 'uk',
}

export enum NotificationEvent {
	NEW_ORDER = 'NEW_ORDER',
	ORDER_STATUS_CHANGE = 'ORDER_STATUS_CHANGE',
	NEW_MESSAGE = 'NEW_MESSAGE',
	MODERATION_RESULT = 'MODERATION_RESULT',
	VERIFICATION_RESULT = 'VERIFICATION_RESULT',
	COMPLAINT_UPDATE = 'COMPLAINT_UPDATE',
	REVIEW_RECEIVED = 'REVIEW_RECEIVED',
	SUPPORT_UPDATE = 'SUPPORT_UPDATE',
}

export enum ImportStatus {
	PENDING = 'PENDING',
	VALIDATED = 'VALIDATED',
	PROCESSING = 'PROCESSING',
	COMPLETED = 'COMPLETED',
	FAILED = 'FAILED',
}
