import {
	faHome,
	faSearch,
	faShoppingCart,
	faUser,
	faBox,
	faBoxes,
	faTags,
	faTag,
	faClipboardList,
	faChartBar,
	faChartLine,
	faUpload,
	faDownload,
	faEdit,
	faTrash,
	faTrashAlt,
	faPlus,
	faMinus,
	faTimes,
	faCheck,
	faCheckCircle,
	faTimesCircle,
	faExclamationTriangle,
	faInfoCircle,
	faQuestionCircle,
	faBell,
	faBellSlash,
	faEnvelope,
	faLock,
	faUnlock,
	faEye,
	faEyeSlash,
	faAngleLeft,
	faAngleRight,
	faAngleUp,
	faAngleDown,
	faChevronLeft,
	faChevronRight,
	faStar,
	faStarHalfAlt,
	faHeart,
	faShare,
	faFilter,
	faSort,
	faSortUp,
	faSortDown,
	faEllipsisV,
	faEllipsisH,
	faSync,
	faSpinner,
	faBan,
	faFlag,
	faShield,
	faBuilding,
	faStore,
	faGripVertical,
	faCircleCheck,
	faTruck,
	faMapMarkerAlt,
	faPhone,
	faCamera,
	faImage,
	faFileCsv,
	faFileExcel,
	faFileAlt,
	faGlobe,
	faCog,
	faSignOutAlt,
	faSignInAlt,
	faUserPlus,
	faUserShield,
	faUsers,
	faComment,
	faComments,
	faPaperPlane,
	faArrowLeft,
	faArrowRight,
	faExternalLinkAlt,
	faLayerGroup,
	faClipboardCheck,
	faSun,
	faBolt,
	faBars,
	faClock,
	faWallet,
	faPrint,
	faCalendar,
} from '@fortawesome/free-solid-svg-icons';

import {
	faStar as faStarRegular,
	faHeart as faHeartRegular,
} from '@fortawesome/free-regular-svg-icons';

export const Icons = {
	// Navigation
	home: faHome,
	search: faSearch,
	cart: faShoppingCart,
	user: faUser,
	arrowLeft: faArrowLeft,
	arrowRight: faArrowRight,
	angleLeft: faAngleLeft,
	angleRight: faAngleRight,
	angleUp: faAngleUp,
	angleDown: faAngleDown,
	chevronLeft: faChevronLeft,
	chevronRight: faChevronRight,
	externalLink: faExternalLinkAlt,

	// Products
	product: faBox,
	products: faBoxes,
	category: faTags,
	tag: faTag,
	image: faImage,
	camera: faCamera,

	// Orders & Commerce
	order: faClipboardList,
	truck: faTruck,
	location: faMapMarkerAlt,

	// Analytics
	chart: faChartBar,
	chartLine: faChartLine,

	// Actions
	edit: faEdit,
	delete: faTrash,
	deleteSoft: faTrashAlt,
	add: faPlus,
	minus: faMinus,
	close: faTimes,
	check: faCheck,
	upload: faUpload,
	download: faDownload,
	filter: faFilter,
	sort: faSort,
	sortUp: faSortUp,
	sortDown: faSortDown,
	sync: faSync,
	more: faEllipsisV,
	moreH: faEllipsisH,

	// Status
	success: faCheckCircle,
	error: faTimesCircle,
	warning: faExclamationTriangle,
	info: faInfoCircle,
	question: faQuestionCircle,
	ban: faBan,
	flag: faFlag,
	spinner: faSpinner,

	// Notifications & Comm
	bell: faBell,
	bellOff: faBellSlash,
	envelope: faEnvelope,
	chat: faComment,
	chats: faComments,
	send: faPaperPlane,
	phone: faPhone,

	// Auth & Security
	lock: faLock,
	unlock: faUnlock,
	eye: faEye,
	eyeOff: faEyeSlash,
	shield: faShield,
	signIn: faSignInAlt,
	signOut: faSignOutAlt,
	userPlus: faUserPlus,
	userShield: faUserShield,
	users: faUsers,

	// Review
	star: faStar,
	starHalf: faStarHalfAlt,
	starEmpty: faStarRegular,
	heart: faHeart,
	heartEmpty: faHeartRegular,
	share: faShare,

	// Files
	fileCsv: faFileCsv,
	fileExcel: faFileExcel,
	file: faFileAlt,

	// Misc
	building: faBuilding,
	store: faStore,
	grip: faGripVertical,
	checkCircle: faCircleCheck,
	globe: faGlobe,
	settings: faCog,
	layers: faLayerGroup,
	clipboardCheck: faClipboardCheck,
	sun: faSun,
	bolt: faBolt,
	listView: faBars,
	clock: faClock,
	wallet: faWallet,
	print: faPrint,
	calendar: faCalendar,
} as const;
