export enum PayoutSchedule {
	WEEKLY_TUESDAY = 'WEEKLY_TUESDAY',
	BIWEEKLY = 'BIWEEKLY',
	MONTHLY_FIRST = 'MONTHLY_FIRST',
	ON_DEMAND = 'ON_DEMAND',
}

export const DEFAULT_COMMISSION_PERCENT = 12;
export const DEFAULT_COMMISSION_FIXED_FEE = 0.5;
export const DEFAULT_PAYOUT_CURRENCY = 'USD';
